### ISSUE TITLE
Mushaf Layout - {{ 13 lines Tadjweed }}

### ISSUE THREAD

**Issue by Baraw** [TarteelAI/quranic-universal-library#118]
### Mushaf PDF URL

https://archive.org/details/13-line-quran-with-beautiful-color-coded-tajwid-rules-pdf

### Number of Pages

850

### Lines Per Page

13

### Layout Information

It looks like the others 13-lines quran but the page number is +2

### Why Should We Add This Layout?

It is commonly used in the south Asian area.
It is colored for Tadjweed.

**Comment by naveed-ahmad** [comment]
Indopak 13 lines layout is already available in QUL, this layout has 849 pages and hopefully will serve the purpose. We don't have indoapak script with tajweed annotation, will add it but that's a separate issue.

https://qul.tarteel.ai/mushaf_layouts/17?page_number=2&source_pdf=true

**Comment by Baraw** [comment]
Is the text-layout mushaf available for download or use ?

**Comment by naveed-ahmad** [comment]
You can download the layout data as a SQLite database from [this link](https://qul.tarteel.ai/resources/mushaf-layout#downloadable_resource_236). The layout data contains metadata for each page. The Indopak 13-line layout has 849 pages and 11,020 lines. In the database, you'll find metadata for each line.

The `line_type` column indicates what should be rendered on that line:

- If the value is `surah_name`, you'll render the surah name on that line. The `surah_number` column contains the surah ID.
- If the value is `basmallah`, you'll render "Bismillah."
- If the value is `ayah`, it means you'll render an ayah on that line. The `first_word_id` and `last_word_id` columns define the range of words for that line.
- The `is_centered` column indicates whether the line should be center-aligned or justified.


You can use Layout data + Word by word script + fonts to render musahf page. Script is also available on resources page. Fonts will be available soon.

**Comment by rahmanifelsetech** [comment]
Do we have any comprehensive list of combination to be used ideally

Such as which Layout data + Word by word script + fonts to be used together ?
