### ISSUE TITLE
Juz 20 mistake, Quran.com tajweed font

### ISSUE THREAD

**Issue by z1409** [TarteelAI/quranic-universal-library#148]
### Surah Number

29

### Ayah Number

38

### Script Type

Other

### Detailed Description of the Issue

Mistake in the new tajweed font on Quran.com. The madd in the word "masaakinihim" has been coloured grey, which suggests that it is silent and not to be pronounced. This is **incorrect** and **changes the word**. The madd is pronounced as a normal 2 count madd and should therefore be coloured mustard.

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting, fixed now. 

![image](https://github.com/user-attachments/assets/4747989d-b687-4654-a5de-3814d7560a76)
