### ISSUE TITLE
Font site cannot be accessible: https://qul.tarteel.ai/resources/font

### ISSUE THREAD

**Issue by luthfilq** [TarteelAI/quranic-universal-library#162]
### Surah Number

0

### Ayah Number

0

### Script Type

Other

### Detailed Description of the Issue

All fonts cannot be accessible because this site is error when I access it: https://qul.tarteel.ai/resources/font

here is the screenshot of error

thank you

<img width="957" alt="Screenshot 2024-11-25 at 06 22 51" src="https://github.com/user-attachments/assets/a9c39cca-f922-4e84-983a-f9fa6acfe408">

**Comment by naveed-ahmad** [comment]
JAK for reporting, it's fixed now.

**Comment by luthviar** [comment]
thank you brother @naveed-ahmad
