### ISSUE TITLE
Resource download is not working

### ISSUE THREAD

**Issue by Ysajid** [TarteelAI/quranic-universal-library#174]
The download buttons are not working (both sqlite and json) from [this page](https://qul.tarteel.ai/resources/recitation)

Browser: Firefox
OS: Ubuntu 24.04 LTS

![image](https://github.com/user-attachments/assets/f3aaa984-a05d-41d9-95c8-015a9232880e)

**Comment by Ysajid** [comment]
https://s3.us-east-1.wasabisys.com/static-cdn.tarteel.ai/qul-exports/recitation/1722845783-m9fu9-ayah-recitation-mohamed-siddiq-al-minshawi-recitation-mujawwad-hafs-71.db.bz2

I've recorded an audio as well. It seems the request is complete, but the file is not being downloaded in my browser.


https://github.com/user-attachments/assets/7f9fff0b-b35e-43f8-8e59-550c519db080

**Comment by naveed-ahmad** [comment]
@Ysajid can you try again?

**Comment by Ysajid** [comment]
Working perfectly @naveed-ahmad 
/close

**Comment by Ysajid** [comment]
Working perfectly @naveed-ahmad. JazakAllahu khayr.
