### ISSUE TITLE
UI - Placement of Alerts/Messaging

### ISSUE THREAD

**Issue by umxr** [TarteelAI/quranic-universal-library#68]
Noticed some inconsistencies of where notice messages are positioned on the site. On this page https://qul.tarteel.ai/tools. They are placed at the top, which is fine.

<img width="1465" alt="Screenshot 2024-08-18 at 10 09 40" src="https://github.com/user-attachments/assets/8725ec28-00a0-4afa-8a23-76cf3c3a84e2">

However, on the resources landing page, The messaging is placed at the bottom. https://qul.tarteel.ai/resources
<img width="1467" alt="Screenshot 2024-08-18 at 10 11 11" src="https://github.com/user-attachments/assets/cb237385-aaea-4f02-8a7d-9715b07f3f2e">

Having the notice message at the bottom would cause a lot of users to miss this. Also i would consider adjusting the colour of the message. The red suggests some form of error, but that could just be how im interpreting it at a glance

**Comment by andresuchdata** [comment]
I'll try to check it.
