### ISSUE TITLE
UI - Parsing/Rendering of Resource Tags

### ISSUE THREAD

**Issue by umxr** [TarteelAI/quranic-universal-library#69]
Noticed a small discrepancy when comparing 2 resource cards. 

<img width="499" alt="Screenshot 2024-08-18 at 15 21 28" src="https://github.com/user-attachments/assets/c4eb15c1-ce67-4e32-8059-60e22be71d95">
<img width="494" alt="Screenshot 2024-08-18 at 15 21 23" src="https://github.com/user-attachments/assets/6c16c2c3-8973-40dd-90d9-e24b9c2bde7b">

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting. Fixed.
